local collision_mask_util = require("__core__/lualib/collision-mask-util")
local data_util = require("__flib__/data-util")

data:extend({
  {
    type = "custom-input",
    name = "tl-get-tool",
    key_sequence = "ALT + M",
    action = "spawn-item",
    item_to_spawn = "tl-tool",
    order = "a",
  },
  {
    type = "custom-input",
    name = "tl-edit-tape",
    key_sequence = "mouse-button-2",
    order = "b",
  },
  {
    type = "custom-input",
    name = "tl-delete-tape",
    key_sequence = "SHIFT + mouse-button-2",
    order = "c",
  },
  {
    type = "custom-input",
    name = "tl-increase-divisor",
    key_sequence = "SHIFT + mouse-wheel-up",
    order = "d",
  },
  {
    type = "custom-input",
    name = "tl-decrease-divisor",
    key_sequence = "SHIFT + mouse-wheel-down",
    order = "e",
  },
  {
    type = "custom-input",
    name = "tl-next-mode",
    key_sequence = "CONTROL + mouse-wheel-up",
    order = "f",
  },
  {
    type = "custom-input",
    name = "tl-previous-mode",
    key_sequence = "CONTROL + mouse-wheel-down",
    order = "g",
  },
  {
    type = "custom-input",
    name = "tl-clear-cursor",
    key_sequence = "",
    linked_game_control = "clear-cursor",
  },
  {
    type = "simple-entity-with-force",
    name = "tl-dummy-entity",
    flags = { "not-on-map", "hidden", "player-creation" },
    collision_box = { { -0.4, -0.4 }, { 0.4, 0.4 } },
    collision_mask = { collision_mask_util.get_first_unused_layer() },
    selectable_in_game = false,
    picture = {
      filename = data_util.empty_image,
      width = 8,
      height = 8,
    },
    build_sound = {
      filename = "__core__/sound/silence-1sec.ogg",
    },
    created_smoke = { smoke_name = "tl-empty-smoke" },
    alert_when_damaged = false,
  },
  {
    type = "highlight-box",
    name = "tl-highlight-box",
  },
  {
    type = "selection-tool",
    name = "tl-tool",
    localised_name = { "item-name.tl-tool" },
    icons = {
      { icon = data_util.black_image, icon_size = 1, scale = 64 },
      { icon = "__Tapeline__/graphics/item/tapeline-tool.png", icon_size = 32, icon_mipmaps = 2 },
    },
    subgroup = "tool",
    order = "c[automated-construction]-x",
    selection_mode = { "nothing" },
    alt_selection_mode = { "nothing" },
    selection_color = { a = 0 },
    alt_selection_color = { a = 0 },
    selection_cursor_box_type = "not-allowed",
    alt_selection_cursor_box_type = "not-allowed",
    place_result = "tl-dummy-entity",
    stack_size = 10,
    flags = { "hidden", "only-in-cursor", "spawnable" },
    draw_label_for_cursor_render = true,
    mouse_cursor = "tl-tool-cursor",
  },
  {
    type = "mouse-cursor",
    name = "tl-tool-cursor",
    filename = "__Tapeline__/graphics/cursor/draw-cursor.png",
    hot_pixel_x = 1,
    hot_pixel_y = 1,
  },
  {
    type = "shortcut",
    name = "tl-get-tool",
    order = "a[alt-mode]-b[copy]",
    associated_control_input = "tl-get-tool",
    action = "spawn-item",
    item_to_spawn = "tl-tool",
    icon = {
      filename = "__Tapeline__/graphics/shortcut/shortcut-x32.png",
      y = 0,
      size = 32,
      mipmap_count = 2,
      flags = { "icon" },
    },
    disabled_icon = {
      filename = "__Tapeline__/graphics/shortcut/shortcut-x32.png",
      y = 32,
      size = 32,
      mipmap_count = 2,
      flags = { "icon" },
    },
    small_icon = {
      filename = "__Tapeline__/graphics/shortcut/shortcut-x24.png",
      y = 0,
      size = 24,
      mipmap_count = 2,
      flags = { "icon" },
    },
    disabled_small_icon = {
      filename = "__Tapeline__/graphics/shortcut/shortcut-x24.png",
      y = 24,
      size = 24,
      mipmap_count = 2,
      flags = { "icon" },
    },
  },
  {
    type = "tips-and-tricks-item-category",
    name = "tapeline",
    order = "l-[tapeline]",
  },
  {
    type = "tips-and-tricks-item",
    name = "tl-introduction",
    category = "tapeline",
    order = "a",
    is_title = true,
    trigger = { type = "dependencies-met" },
    image = "__Tapeline__/graphics/tips-and-tricks/introduction.png",
  },
  {
    type = "tips-and-tricks-item",
    name = "tl-persistent",
    category = "tapeline",
    order = "b",
    indent = 1,
    dependencies = { "tl-introduction" },
    trigger = { type = "dependencies-met" },
    image = "__Tapeline__/graphics/tips-and-tricks/persistent.png",
  },
  {
    type = "tips-and-tricks-item",
    name = "tl-modes",
    category = "tapeline",
    order = "c",
    indent = 1,
    dependencies = { "tl-introduction" },
    trigger = { type = "dependencies-met" },
    image = "__Tapeline__/graphics/tips-and-tricks/modes.png",
  },
  {
    type = "tips-and-tricks-item",
    name = "tl-divisors",
    category = "tapeline",
    order = "d",
    indent = 1,
    dependencies = { "tl-introduction" },
    trigger = { type = "dependencies-met" },
    image = "__Tapeline__/graphics/tips-and-tricks/divisors.png",
  },
  {
    type = "tips-and-tricks-item",
    name = "tl-edit",
    category = "tapeline",
    order = "e",
    indent = 1,
    dependencies = { "tl-introduction" },
    trigger = { type = "dependencies-met" },
    image = "__Tapeline__/graphics/tips-and-tricks/edit.png",
  },
  {
    type = "trivial-smoke",
    name = "tl-empty-smoke",
    animation = {
      filename = data_util.empty_image,
      size = { 1, 1 },
      frame_count = 8,
    },
    duration = 1,
  },
})
