require("prototypes.custom-input")
require("prototypes.entity")
require("prototypes.item")
require("prototypes.mouse-cursor")
require("prototypes.shortcut")
require("prototypes.tips-and-tricks")
require("prototypes.trivial-smoke")